- name: apt install dnsmasq
  apt:
    name: dnsmasq
    update_cache: yes

- name: save /etc/dnsmasq.conf
  template:
    src: dnsmasq.conf.j2
    dest: /etc/dnsmasq.conf
    owner: root
    group: root
    mode: 0644

- name: systemctl start dnsmasq
  systemd:
   name: dnsmasq
   state: started

- name: iptables -A INPUT dns udp
  iptables:
    chain: INPUT
    in_interface: "{{ interface_internal }}"
    protocol: udp
    destination_port: "53"
    jump: ACCEPT
  notify: persist iptables

- name: iptables -A INPUT dns tcp
  iptables:
    chain: INPUT
    in_interface: "{{ interface_internal }}"
    protocol: tcp
    destination_port: "53"
    jump: ACCEPT
  notify: persist iptables

- name: iptables -A INPUT dhcp
  iptables:
    chain: INPUT
    in_interface: "{{ interface_internal }}"
    protocol: udp
    destination_port: "67"
    jump: ACCEPT
  notify: persist iptables
