- name: net.ipv4.ip_forward = 1
  sysctl:
    name: net.ipv4.ip_forward
    value: "1"
    sysctl_set: yes
    state: present
    reload: yes

- name: install iptables-persistent
  apt:
    name: iptables-persistent
    update_cache: yes
    autoremove: yes

- name: iptables MASQUERADE
  iptables:
    table: nat
    chain: POSTROUTING
    out_interface: "{{ interface_external }}"
    jump: MASQUERADE
  notify: persist iptables

- name: iptables FORWARD
  iptables:
    chain: FORWARD
    in_interface: "{{interface_external}}"
    out_interface: "{{interface_internal}}"
    ctstate: ESTABLISHED,RELATED
    jump: ACCEPT
  notify: persist iptables

- name: iptables FORWARD
  iptables:
    chain: FORWARD
    in_interface: "{{interface_internal}}"
    out_interface: "{{interface_external}}"
    jump: ACCEPT
  notify: persist iptables
