- sysctl:
    name: net.ipv4.ip_forward
    value: "1"
    sysctl_set: yes
    state: present
    reload: yes

- apt:
    name: iptables-persistent
    update_cache: yes
    autoremove: yes

- iptables:
    table: nat
    chain: POSTROUTING
    out_interface: "{{ interface_external }}"
    jump: MASQUERADE
  notify: persist iptables

- iptables:
    chain: FORWARD
    in_interface: "{{interface_external}}"
    out_interface: "{{interface_internal}}"
    ctstate: ESTABLISHED,RELATED
    jump: ACCEPT
  notify: persist iptables

- iptables:
    chain: FORWARD
    in_interface: "{{interface_internal}}"
    out_interface: "{{interface_external}}"
    jump: ACCEPT
  notify: persist iptables
