- hosts: all
  gather_facts: false
  become: true
  vars:
    #ansible_connection: ssh
    ansible_ssh_user: user
    ansible_ssh_pass: user
    ansible_sudo_pass: user
    # Interface for internet connection.
    interface_external: ens33
    # Interface for internal network
    interface_internal: ens37
    # application config
    dnsmasq_dhcp_range: 192.168.3.50,192.168.3.150,255.255.255.0,12h
    squid_localnet_src: 192.168.3.0/255.255.255.0
  roles:
  - router
  - dnsmasq
  - squid
