- iptables:
    chain: INPUT
    ctstate: ESTABLISHED,RELATED
    jump: ACCEPT

- iptables:
    chain: INPUT
    in_interface: "{{ interface_internal }}"
    protocol: tcp
    destination_port: "22"
    ctstate: NEW
    syn: match
    jump: ACCEPT
  notify: persist iptables

- iptables:
    chain: INPUT
    in_interface: "lo"
    protocol: tcp
    destination_port: "22"
    ctstate: NEW
    syn: match
    jump: ACCEPT
  notify: persist iptables

- iptables:
    chain: INPUT
    policy: DROP
  notify: persist iptables

- iptables:
    chain: FORWARD
    policy: DROP
  notify: persist iptables

