- name: apt install squid
  apt:
    name: squid
    update_cache: yes

- name: save /etc/squid/squid.conf
  template:
    src: squid.conf.j2
    dest: /etc/squid/squid.conf
    owner: root
    group: root
    mode: 0644
  notify: restart squid

- name: mkdir /var/spool/squid
  file:
    path: /var/spool/squid
    state: directory
    owner: proxy
    group: proxy
    mode: 0755

- name: apt install iptables-persistent
  apt:
    name: iptables-persistent
    update_cache: yes
    autoremove: yes

- name: iptables -t nat -A PREROUTING REDIRECT
  iptables:
    table: nat
    chain: PREROUTING
    in_interface: "{{ interface_internal }}"
    protocol: tcp
    destination_port: "80"
    jump: REDIRECT
    to_ports: "3128"
  notify: persist iptables

- name: iptables -A INPUT 3128
  iptables:
    chain: INPUT
    in_interface: "{{ interface_internal }}"
    protocol: tcp
    destination_port: "3128"
    jump: ACCEPT
  notify: persist iptables

- name: systemctl restart squid
  systemd:
    name: squid
    state: started
    enabled: yes
    daemon-reload: yes
